### ISSUE TITLE
List of system dependencies

### ISSUE THREAD

**Issue by danijar** [ppaquette/gym-doom#2]
I think providing a list of system dependencies would be helpful for many people. For Ubuntu 14.04, this seems to work for me:

``` sh
sudo apt-get install -y gtk2.0-dev libsdl2-dev libfluidsynth-dev libopenal-dev libboost-all-dev
```

If someone else can confirm, we can probably include this in the readme.

**Comment by ppaquette** [comment]
Depends on `gym` and `doom-py` dependencies:

```
apt-get install -y python-numpy cmake zlib1g-dev libjpeg-dev libboost-all-dev gcc libsdl2-dev wget unzip git
```
