### ISSUE TITLE
Currently all IDs must be of the form ^([\w:-]+)-v(\d+)$.)

### ISSUE THREAD

**Issue by frala19871987** [ppaquette/gym-doom#5]
Hi,
if I use env = gym.make('ppaquette/DoomBasic-v0') I have the following error:

```
Currently all IDs must be of the form ^([\w:-]+)-v(\d+)$.)
```

Any idea on how to fix it?

Thanks

**Comment by ppaquette** [comment]
You need to import gym_pull first, to allow env names to have the format username/envName-v0.

**Comment by ppaquette** [comment]
Fixed in gym 0.4.10

**Comment by frala19871987** [comment]
Hi,
all fixed :)

Thanks
