### ISSUE TITLE
How can I move the player?

### ISSUE THREAD

**Issue by frala19871987** [ppaquette/gym-doom#6]
Hi
please, can you show me how to move the player left, right and show for the DoomBasic-v0? I understand that it needs an action made of 43 integer ..

Thanks

**Comment by ppaquette** [comment]
To move left:

```
actions = [0] * 43   # Create an array of 43 zeros
actions[11] = 1      # MOVE_LEFT (Set index 11 to 1)
```

This will create an array where item with index 11 is 1 (i.e. [0,0,0..,0,1,0,...,0,0,0]

Use
set index 0 to `1` for ATTACK
set index 10 to `1` for MOVE_RIGHT
set index 11 to `1` for MOVE_LEFT

**Comment by frala19871987** [comment]
Thanks,
an for the other directions? I cannot really understand how to make the player move...

Thanks

**Comment by frala19871987** [comment]
OK thanks I'll try now.

Thanks

**Comment by frala19871987** [comment]
Hi,
I'm sorry to reopen it. Is there a way to see how to describe all the possible movement like left, right, forward, back and shot? I would suggest to maybe create a module for each example you make like mario and doom. I think after that a user could just do player.left() or similar.

Thanks

**Comment by ppaquette** [comment]
There is a [documentation per level](https://github.com/ppaquette/gym-doom/tree/master/ppaquette_gym_doom), and [one documentation for all commands](https://github.com/ppaquette/gym-doom/blob/master/ppaquette_gym_doom/controls.md) (not all commands can be used on all levels).

You can also use a wrapper to convert the action space to a discrete or continuous action space.
