### ISSUE TITLE
Accessing Player Position

### ISSUE THREAD

**Issue by jcoreyes** [ppaquette/gym-doom#9]
Is there a good way to get the agent's position? I tried adding POSITION_X and POSITION_Y to the assets/ENV_NAME.cfg file but it claims those variables are unsupported when the cfg is loaded. It seems like someone was able to do it with VizDoom here https://github.com/mwydmuch/ViZDoom/issues/67 but I'm not sure how to do it for this version of the doom env.

**Comment by ppaquette** [comment]
You are suppose to only use the visual information, otherwise you need to design your own wad. This feature is not possible in gym-doom.
